title: Clint Colding
logo: /assets/img/headshot.jpg
description: I like tech, I sometimes play golf, and I can't wait for December 20th.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Social accounts
twitter: theclintcolding
github: clintcolding
linkedin: clintcolding