title: Clint Colding
author: Clint Colding
url: http://clintcolding.com
description: > # this means to ignore newlines until "baseurl:"
  Just a guy trying to learn new stuff.

twitter_username: theclintcolding
github_username: clintcolding
linkedin_username: clintcolding

google_analytics: UA-102213338-1

disqus:
  shortname: clintcolding

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

gems:
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock