title: Clint Colding
description: My Personal Blog
author: Clint Colding
github: https://github.com/clintcolding
about: 
disqus_shortname: 
google_analytics: UA-102213338-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/clintcolding"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

# urls:
#     - text: About Me
#       url: /about/
#     - text: My Projects
#       url: /projects/
#     - text: XML Feed
#       url: /feed.xml

url: "http://clintcolding.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
