# Site settings
title: "Clint Colding"
description: ""
baseurl: "clintcolding.com" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Clint Colding"

twitter_username: theclintcolding
github_username: clintcolding
linkedin_username: clintcolding

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: