title: Clint Colding
author: Clint Colding
description: > # this means to ignore newlines until "baseurl:"
  I'm a simple guy trying to learn new stuff.

twitter_username: theclintcolding
github_username:  clintcolding

google_analytics: UA-102213338-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
